# Generated by Django 4.1.4 on 2023-09-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_remove_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
